/**
 * Rex SDK for Effect
 *
 * Effect-native SDK for the Rex Software real-estate API, generated from
 * Rex's own `describe` / `describeModel` introspection endpoints.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model
 * in `.generated-specs` (written by `scripts/convert.ts` from the OpenAPI
 * document that `scripts/build-openapi.ts` assembles). Everything else in
 * this folder is hand-written.
 *
 * @example
 * ```ts
 * import * as Rex from "@smartretraining/rex-effect";
 *
 * const page = yield* Rex.listingsSearch({ limit: 3 });
 * ```
 */
export * from "./credentials.ts";
export * as Category from "./category.ts";
export * as T from "./traits.ts";
export * as Retry from "./retry.ts";
export { RexProtocol, type RexOpError, type RexOpContext } from "./protocol.ts";
export * from "./errors.ts";
export * from "./webhooks.ts";
export * as Services from "./services/index.ts";
// Operations (and their request/response types) stay importable straight off
// the package root, as consumers already use them.
export * from "./services/rex.ts";
