/**
 * @smartretraining/vaultre-effect — VaultRE API SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model in
 * `.generated-specs` (written by `scripts/convert.ts` from the vendor OpenAPI
 * document in `specs/`). Everything else in this folder is hand-written.
 *
 * @example
 * ```ts
 * import * as Effect from "effect/Effect";
 * import * as Vaultre from "@smartretraining/vaultre-effect";
 *
 * const program = Effect.gen(function* () {
 *   const page = yield* Vaultre.getSaleProperties({ pagesize: 10 });
 *   return page.items;
 * }).pipe(
 *   Effect.provide(Vaultre.CredentialsFromEnv),
 * );
 * ```
 */
export * from "./credentials.ts";
export * as Category from "./category.ts";
export * as T from "./traits.ts";
export * as Retry from "./retry.ts";
export {
  VaultreProtocol,
  type VaultreOpError,
  type VaultreOpContext,
} from "./protocol.ts";
export * from "./errors.ts";
export { paginatePages } from "./pagination.ts";
export * as Services from "./services/index.ts";
// Operations (and their request/response types) are importable straight off
// the package root. The service-local typed error classes shadow the
// same-named shared ones from ./errors.ts — the operations actually raise
// the service-local classes, and `export *` from both is TS2308 under the
// release workflow's strict typecheck.
export * from "./services/vaultre.ts";
export {
  BadRequest,
  Forbidden,
  NotFound,
  UnprocessableEntity,
} from "./services/vaultre.ts";
