/**
 * @smartretraining/reapit-effect — Reapit Sales API (Agentbox) SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model in
 * `.generated-specs` (written by `scripts/convert.ts` from the vendor OpenAPI
 * document plus the repair patches in `patches/`). Everything else in this
 * folder is hand-written.
 *
 * @example
 * ```ts
 * import * as Effect from "effect/Effect";
 * import * as Reapit from "@smartretraining/reapit-effect";
 *
 * const program = Effect.gen(function* () {
 *   const page = yield* Reapit.getListings({ limit: 10 });
 *   return page.listings;
 * }).pipe(
 *   Effect.provide(Reapit.CredentialsFromEnv),
 * );
 * ```
 */
export * from "./credentials.ts";
export * as Category from "./category.ts";
export * as T from "./traits.ts";
export * as Retry from "./retry.ts";
export {
  ReapitProtocol,
  type ReapitOpError,
  type ReapitOpContext,
} from "./protocol.ts";
export * from "./errors.ts";
export { paginatePages } from "./pagination.ts";
export * as Services from "./services/index.ts";
// Operations (and their request/response types) are importable straight off
// the package root. The service-local typed error classes shadow the
// same-named shared ones from ./errors.ts — the operations actually raise
// the service-local classes.
export * from "./services/reapit.ts";
export { NotFound, UnprocessableEntity } from "./services/reapit.ts";
