/**
 * @smartretraining/boxdice-effect — Box+Dice (MRI) AI API SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model in
 * `.generated-specs` (written by `scripts/convert.ts` from the OpenAPI
 * document that `scripts/build-spec.ts` transcribes from Box+Dice's published
 * API Blueprint). Everything else in this folder is hand-written.
 *
 * The response schemas have NOT been verified against a live tenant — see
 * README.md, which lists what to check first when a key arrives.
 *
 * @example
 * ```ts
 * import * as Effect from "effect/Effect";
 * import * as Stream from "effect/Stream";
 * import * as BoxDice from "@smartretraining/boxdice-effect";
 *
 * const program = Stream.runCollect(
 *   BoxDice.listSalesListings.pages({}).pipe(
 *     Stream.flatMap((page) => Stream.fromIterable(page.data ?? [])),
 *   ),
 * ).pipe(
 *   Effect.provide(BoxDice.fromToken({ tenant: "acme", token: "..." })),
 * );
 * ```
 */
export * from "./credentials.ts";
export * as Category from "./category.ts";
export * as T from "./traits.ts";
export * as Retry from "./retry.ts";
export {
  BoxDiceProtocol,
  normaliseEmptyBody,
  type BoxDiceOpError,
  type BoxDiceOpContext,
} from "./protocol.ts";
export * from "./errors.ts";
export { paginateAfter, nextCursor } from "./pagination.ts";
export * as Services from "./services/index.ts";
// Operations (and their request/response types) are importable straight off
// the package root. The service-local typed error classes shadow the
// same-named shared ones from ./errors.ts — the operations actually raise
// the service-local classes.
export * from "./services/boxdice.ts";
export { BadRequest } from "./services/boxdice.ts";
